apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-crud-service.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-crud-service.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.env.ENVIRONMENT | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  SERVER_PORT: {{ .Values.env.SERVER_PORT | quote }}
  OTEL_SERVICE_NAME: {{ .Values.env.OTEL_SERVICE_NAME | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.env.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
