{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "go-crud-service.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-crud-service.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  # Azure Workload Identity label — required for the mutating webhook to inject credentials
  labels:
    azure.workload.identity/use: "true"
{{- end }}
