replicaCount: 1

image:
  repository: go-crud-service
  tag: "latest"
  pullPolicy: Never

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  ENVIRONMENT: dev
  LOG_LEVEL: debug
  SERVER_PORT: "8080"
  OTEL_SERVICE_NAME: go-crud-service
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger.monitoring.svc.cluster.local:4317"

serviceMonitor:
  enabled: true

autoscaling:
  enabled: false
